### ISSUE TITLE
Stuck in "Enter the four digits displayed on your TV:" loop

### ISSUE THREAD

**Issue by panagiotisTB** [nikagl/hisense#1]
hey @nikagl, quick FYI: I just tried this script to control my VIDAA based TV. Sadly, for some reason, it's getting stuck in a loop. I guess something is wrong with the authentication. I will investigate in the coming days.

Model: Hisense 65U6NQ
Software Version: V0000.07.60L.O0319

**Comment by hwijers** [comment]
Same here:
Model: Hisense 75U79NQ
Software Version: V0000.08.50A.00713

**Comment by nikagersonlohman** [comment]
It still works for me:

Model: Hisense 65E7KQ
Software version: V0010.06.30B.N0908
Long version: C.N0908

In system update it says it's the latest version for my TV...

**Comment by Saggerus** [comment]
Same issue
Model: 75U6NQ
SV: V0000.07.601.O0410
EV: I.O0410

**Comment by Saggerus** [comment]
> Same issue Model: 75U6NQ SV: V0000.07.601.O0410 EV: I.O0410

So, for some reason, running it with --debug True got it working for me, however with a few quirks:

Options 1 - 5 all work fine

Option 6 fails with:
Traceback (most recent call last):
  File "C:\Users\wayne\Documents\hi_keys\hisense-main\hisense.py", line 739, in <module>
    volume = get_volume()
             ^^^^^^^^^^
NameError: name 'get_volume' is not defined

If I instead run setvolume from the command line, it reports that the volume has been changed successfully, but it hasn't changed (as verified with getvolume)

Option 7 works fine

Option 8 fails with:
File "C:\Users\wayne\Documents\hi_keys\hisense-main\hisense.py", line 778, in <module>
    app_launched = auth.launch_app(app_name, app_list)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wayne\Documents\hi_keys\hisense-main\hisense.py", line 613, in launch_app
    launch_app_command = json.dumps({"appId": app_id, "name": app_name, "url": app_url})
                                              ^^^^^^
UnboundLocalError: cannot access local variable 'app_id' where it is not associated with a value

I tried both using quotes as per the JSON that appears, and without as per getapplist results.  
launchapp from the command line using an entry from getapplist results in:
Failed to find app in app list.
Failed to launch app.

**Comment by nikagl** [comment]
Weird, adding the debug just adds debug lines to the output... it works for me with and without the debug flag 🤷‍♂️

For the volume & launch app I haven't used/tested them as I don't need it, however I made some changes and it works now (see  https://github.com/nikagl/hisense/commit/aaef1b334f7fa36565c0fbc9dddb83a13131a7ee#diff-d65d80c98e3edd7f77de389ee05cda702974835e8bff3ea13f34c3716c3a45df)

**Comment by Gehetzter** [comment]
Found this amazing script, big thanks to all contributers, I´ve tried it but sadly got stuck in the four digits loop too

Model: Hisense 55E7NQ Pro
Software Version: V0000.08.50A.00713

Python 3.10.7 on Windows
paho-mqtt 1.6.1

```
Initializing...
2024-10-19 17:44:02,520 - INFO - Initializing
2024-10-19 17:44:02,521 - INFO - No stored credentials found, starting auth with TV...
2024-10-19 17:44:02,522 - INFO - MAC Address: 04:a3:1f:cf:ae:f4
2024-10-19 17:44:02,523 - INFO - First Hash: 38D65DC30F45109A369A86FCE866A85B
2024-10-19 17:44:02,524 - INFO - Second Hash: 71999975CAF5B7926ED1796715D96CB2
2024-10-19 17:44:02,525 - INFO - Third Hash: E11C3113BA7285BBC64CAFA18CFB3055
2024-10-19 17:44:02,526 - INFO - Fourth Hash: 95710AABFB9FE9FFEA19F33D1434C79D
2024-10-19 17:44:02,527 - INFO - Client ID: 04:a3:1f:cf:ae:f4$his$719999_vidaacommon_001
2024-10-19 17:44:02,528 - INFO - Creating MQTT client...
2024-10-19 17:44:02,536 - INFO - Adding callback messages for authentication...
2024-10-19 17:44:02,626 - INFO - Connected to MQTT broker
Waiting for message... (press and hold escape to cancel waiting)
Waiting...
2024-10-19 17:44:03,549 - INFO - Publishing message to actions/vidaa_app_connect...
2024-10-19 17:44:03,550 - INFO - Published message 2
2024-10-19 17:44:03,593 - INFO - Authentication message received: "" on topic /remoteapp/mobile/04:a3:1f:cf:ae:f4$his$719999_vidaacommon_001/ui_service/data/authentication
Waiting for message... (press and hold escape to cancel waiting)
Waiting...
2024-10-19 17:44:04,563 - INFO - Subscribing to /remoteapp/mobile/04:a3:1f:cf:ae:f4$his$719999_vidaacommon_001/ui_service/data/authenticationcode...
Enter the four digits displayed on your TV: 5364
2024-10-19 17:44:14,002 - INFO - Published message 4
2024-10-19 17:44:14,007 - INFO - Authentication code message received: {"result":1,"info":"","deviceType":"","always_agree_flag":""} on topic /remoteapp/mobile/04:a3:1f:cf:ae:f4$his$719999_vidaacommon_001/ui_service/data/authenticationcode
Waiting for message... (press and hold escape to cancel waiting)
Waiting...
2024-10-19 17:44:15,065 - ERROR - Problems with the authentication message!
2024-10-19 17:44:15,067 - ERROR - b'{"result":1,"info":"","deviceType":"","always_agree_flag":""}'
Enter the four digits displayed on your TV: 
```

Anything I could try for you to make it work again?

**Comment by nikagl** [comment]
Not sure what that always_agree_flag is? I don't recall seeing that... maybe try linking the Vidaa app to your TV and it asks whether you agree with their terms so it works here too?

**Comment by nikagl** [comment]
The following is from the [Support - VIDAA](https://www.vidaa.com/support/) website:

How can I connect the VIDAA app to my TV?
Take the following steps to connect the VIDAA app to your TV:

Step 1
Make sure your mobile device and TV are connected to the same network.

Step 2
Agree to the VIDAA End User License, Disclaimer, and Privacy Policies on your TV if you haven’t already. To do so, go to your TV settings and select Support > Disclaimer and Privacy.

**Comment by Gehetzter** [comment]
> Not sure what that always_agree_flag is? I don't recall seeing that... maybe try linking the Vidaa app to your TV and it asks whether you agree with their terms so it works here too?

I am already connected by the vidaa app, although I hadn't accepted all of the terms like voice assistant and whatever...

> The following is from the [Support - VIDAA](https://www.vidaa.com/support/) website:
> 
> How can I connect the VIDAA app to my TV? Take the following steps to connect the VIDAA app to your TV:
> 
> Step 1 Make sure your mobile device and TV are connected to the same network.
> 
> Step 2 Agree to the VIDAA End User License, Disclaimer, and Privacy Policies on your TV if you haven’t already. To do so, go to your TV settings and select Support > Disclaimer and Privacy.

Checked all terms now but still no luck.

**Comment by Gehetzter** [comment]
@nikagl @panagiotisTB @hwijers 
The response just got 2 more attributes that I believe are not relevant for us.
Please try changing line 359 from:
```
if json.loads(self.authentication_code_payload.payload.decode()) != {"result": 1, "info": ""}:
```
to
```
payload = json.loads(self.authentication_code_payload.payload.decode())
if not 'result' in payload or payload['result'] != 1:
```

**Comment by nikagl** [comment]
I have created a pull request and merged it with your suggestion... I won't be able to test it until tonight:
https://github.com/nikagl/hisense/pull/3

**Comment by nikagl** [comment]
Any news on connecting to your tv's with the new code (result = 1 instead of the entire authentication code json)?

For some reason my tv has stopped responding to the status messages...not sure yet what is causing this... 

Regards,

Nika.

**Comment by nikagl** [comment]
Ignore that last comment, status messages worked again after power cycling the tv...

So, @panagiotisTB @hwijers @Saggerus @Gehetzter please try the latest version of the code and let me know how it works. Would love to get this issue closed ;)

**Comment by hwijers** [comment]
> Same here: Model: Hisense 75U79NQ Software Version: V0000.08.50A.00713

Just tested and it works with the latest code. No firmware update has been done yet. Now let's see if I can control the TV from mqtt-explorer. Not working yet... thanks!

**Comment by nikagl** [comment]
> > Same here: Model: Hisense 75U79NQ Software Version: V0000.08.50A.00713
> 
> Just tested and it works with the latest code. No firmware update has been done yet. Now let's see if I can control the TV from mqtt-explorer. Not working yet... thanks!

I had to fiddle a lot with MQTT explorer to get it working, it eventually worked but is a bit of a funky interface.... using MQTT explorer I have figured out which calls worked and which didn't...

**Comment by hwijers** [comment]
> > > Same here: Model: Hisense 75U79NQ Software Version: V0000.08.50A.00713
> > 
> > 
> > Just tested and it works with the latest code. No firmware update has been done yet. Now let's see if I can control the TV from mqtt-explorer. Not working yet... thanks!
> 
> I had to fiddle a lot with MQTT explorer to get it working, it eventually worked but is a bit of a funky interface.... using MQTT explorer I have figured out which calls worked and which didn't...

I'm still trying to see if I can do it from the command line, but the following doesn't work either:
mosquitto_pub --cert /opt/hisense/rcm_certchain_pem.cer --key /opt/hisense/rcm_pem_privkey.pkcs8 --tls-version tlsv1.2 --insecure -d -h [IP of TV] -p 36669 -P [Password] -u [Username] -t /remoteapp/tv/ui_service/[Client_id]/actions/gettvstate -m 0

Any idea what I'm doing wrong?

**Comment by nikagl** [comment]
Sorry, cant help you there, i haven't used mosquito for this 🤷‍♂️

**Comment by nikagl** [comment]
I am closing this. If this reoccurs, please reopen or open a new issue
