### ISSUE TITLE
More commands

### ISSUE THREAD

**Issue by dim-geo** [nikagl/hisense#5]
Hi, thanks for this project I can connect to my new hisense TV!
Can we get to the menu in order to change picture settings or issue custom commands?

**Comment by nikagl** [comment]
If you know the json for each of those commands I can add it to the code. I have tried it using MQTT Explorer, and added the commands that worked on my tv...

**Comment by dim-geo** [comment]
added support to send any key.
#6

**Comment by nikagl** [comment]
thanks, merged it (and added option to toggle debug in menu as well)
